# Generated by Django 3.2.18 on 2023-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../brown-profile-image_xcia4p', upload_to='photos'),
        ),
    ]
